---
title: "Data Experimentation"
author: "Julian Stone"
date: 12-3-2020
output:
  github_document:
    toc: true
---

```{r library, message=FALSE}
library(tidyverse)
```


```{r load-data, message=FALSE}
game_genres <- "./data/game_genres.csv"
df_genre <- read_csv(game_genres) %>% rename(genre = Genre)

game_ids <- "./data/game_ids.csv"
df_ids <- read_csv(game_ids)

player_data <- "./data/player_data.csv"
df_player <- 
  read_csv(player_data) %>% 
  filter(action == "play") %>% 
  select(user_id, name, hours)
```

```{r summary}
summary(df_genre)
summary(df_ids)
summary(df_player)
```
```{r join-data}
df_game <-
  df_genre %>% 
  left_join(df_ids, by = "appid") %>% 
  select(name, genre) %>% 
  drop_na() %>% 
  unique() %>% 
  mutate(
    name = str_remove(name, ":"),
    name = str_replace(name, "’", "'")
  )

df_data <-
  df_player %>% 
  left_join(df_game, by = "name")

df_data[is.na(df_data)] <- "Unidentified"
```

```{r}
df_data %>% 
  group_by(genre) %>% 
  summarise(
    mean = mean(hours)
  ) %>% 
  mutate(genre = fct_reorder(genre, mean)) %>% 
  ggplot(aes(mean, genre)) +
  geom_col()
```

```{r}
df_data %>% 
  group_by(user_id) %>% 
  summarise(total = sum(hours)) %>% 
  left_join(df_data, by = "user_id") %>% 
  mutate(prop = hours/total) %>% 
  group_by(genre) %>% 
  summarise(avg_pct = mean(prop)) %>% 
  mutate(genre = fct_reorder(genre, avg_pct)) %>% 
  ggplot(aes(avg_pct, genre)) +
  geom_col()
```

```{r}
df_data %>% 
  filter(genre == "Strategy") %>% 
  group_by(name) %>% 
  summarise(
    mean = mean(hours)
  ) %>% 
  mutate(name = fct_reorder(name, mean)) %>% 
  filter(mean > 50) %>% 
  ggplot(aes(mean, name)) +
  geom_col()
```
